"""Agent-facing tool ecosystem for CARVE."""

from .catalog import core_tool_specs
from .inspection import VisualEvidenceStore
from .contracts import (
    PrimitiveOutcome,
    PrimitiveStatus,
    ToolCall,
    ToolEffect,
    ToolExecutionContext,
    ToolResult,
    ToolSpec,
    VerificationReport,
    VerificationStatus,
    reject_direct_action_fields,
    validate_tool_input,
)
from .registry import EmbodiedToolRegistry, ToolHandler, ToolTraceSink
from .memory import VerifiedPrimitiveTrace, VerifiedProcedureCompiler
from .object_memory import GuardedObjectObserver, ObjectEvidenceMemory, ObjectRole
from .reobservation import BoundedObjectReobserver, NativeObjectObserver
from .reference_observer import ReferenceConditionedObjectObserver
from .planning import EmbodiedTaskPlan, PlanStepReceipt, PlanStepStatus
from .progress import (
    GuardedProgressVerifier,
    VisualProgressContext,
    VisualProgressResult,
    VisualStagePredicate,
    build_visual_progress_request,
)
from .trigger_admission import (
    EpisodePolicyFeasibility,
    EpisodeTriggerEvidence,
    InterventionPolicy,
    PolicyFeasibilityDecision,
    MonitorEventThresholds,
    MonitorSample,
    TriggerAdmissionDecision,
    TriggerAdmissionRequirements,
    escalation_candidate_steps,
    recompute_monitor_events,
    simulate_episode_policy,
    validate_policy_feasibility,
    validate_trigger_admission,
)
from .progress_requirements import (
    ConjunctiveProgressContext,
    ConjunctiveProgressResult,
    GuardedConjunctiveProgressVerifier,
    VisualStageRequirements,
)
from .verifier import (
    GroupedVisualObservation,
    GuardedGroupedVisualVerifier,
    GuardedScalarVisualVerifier,
    GuardedVisualVerifier,
    ScalarVisualObservation,
    ScalarVisualPredicate,
    VisualVerificationContext,
    VisualVerificationResult,
    build_grouped_visual_predicate_request,
    build_scalar_visual_predicate_request,
    build_visual_verification_request,
    evaluate_scalar_visual_predicate,
    parse_grouped_visual_observation,
    parse_scalar_visual_observation,
    parse_visual_verification_report,
)
from .runtime import (
    CanonicalToolRuntime,
    EmbodiedToolBindings,
    PrimitiveExecutionReport,
)
from .workspace import RunManifest, RunWorkspace

__all__ = [
    "VisualEvidenceStore",
    "ObjectRole",
    "ObjectEvidenceMemory",
    "GuardedObjectObserver",
    "NativeObjectObserver",
    "ReferenceConditionedObjectObserver",
    "BoundedObjectReobserver",
    "EmbodiedToolRegistry",
    "EmbodiedToolBindings",
    "CanonicalToolRuntime",
    "PrimitiveOutcome",
    "PrimitiveExecutionReport",
    "PrimitiveStatus",
    "RunManifest",
    "RunWorkspace",
    "ToolCall",
    "ToolEffect",
    "ToolExecutionContext",
    "ToolHandler",
    "ToolResult",
    "ToolSpec",
    "ToolTraceSink",
    "VerificationReport",
    "VerificationStatus",
    "VerifiedPrimitiveTrace",
    "VerifiedProcedureCompiler",
    "EmbodiedTaskPlan",
    "PlanStepReceipt",
    "PlanStepStatus",
    "GuardedVisualVerifier",
    "GuardedProgressVerifier",
    "VisualProgressContext",
    "VisualProgressResult",
    "VisualStagePredicate",
    "build_visual_progress_request",
    "ConjunctiveProgressContext",
    "ConjunctiveProgressResult",
    "GuardedConjunctiveProgressVerifier",
    "VisualStageRequirements",
    "GuardedScalarVisualVerifier",
    "GuardedGroupedVisualVerifier",
    "GroupedVisualObservation",
    "ScalarVisualObservation",
    "ScalarVisualPredicate",
    "VisualVerificationContext",
    "VisualVerificationResult",
    "build_grouped_visual_predicate_request",
    "build_scalar_visual_predicate_request",
    "build_visual_verification_request",
    "evaluate_scalar_visual_predicate",
    "parse_grouped_visual_observation",
    "parse_scalar_visual_observation",
    "parse_visual_verification_report",
    "EpisodePolicyFeasibility",
    "EpisodeTriggerEvidence",
    "InterventionPolicy",
    "PolicyFeasibilityDecision",
    "MonitorEventThresholds",
    "MonitorSample",
    "TriggerAdmissionDecision",
    "TriggerAdmissionRequirements",
    "escalation_candidate_steps",
    "recompute_monitor_events",
    "simulate_episode_policy",
    "validate_policy_feasibility",
    "validate_trigger_admission",
    "core_tool_specs",
    "reject_direct_action_fields",
    "validate_tool_input",
]
