import numpy as np
import logging

logger = logging.getLogger("Pi0Executor")

class Pi0VLAExecutor:
    """
    A wrapper around the openpi (pi0) VLA model to be used by the ExecutionAgent.
    This acts as the Action Expert that decodes visually prompted inputs into 
    continuous Action Chunks.
    """
    def __init__(self, checkpoint_path=None):
        self.checkpoint_path = checkpoint_path
        self.is_loaded = False
        logger.info(f"Initializing Pi0 VLA Executor. Checkpoint: {checkpoint_path}")
        self._load_model()
        
    def _load_model(self):
        """
        Dynamically load the pi0 model from openpi.
        In the real Libero setup, this will invoke `openpi.policies.droid_policy` or similar.
        """
        try:
            # Check if openpi is available in the environment
            import openpi
            from openpi.policies import policy_config
            from openpi.models import model as openpi_model
            
            # Use pi0-base model by default, or specific checkpoint
            model_name = self.checkpoint_path if self.checkpoint_path else "pi0-base"
            logger.info(f"Loading real pi0 weights: {model_name}...")
            
            # Since openpi requires specific environments, we wrap the loading
            # It downloads from HF if not local: `physical-intelligence/pi0-base`
            self.model = openpi_model.load(model_name)
            self.is_loaded = True
            logger.info("Pi0 model (Action Expert) loaded successfully via real openpi package.")
        except ImportError:
            self.is_loaded = False
            logger.warning("openpi package not found. Using mock Pi0 model.")
        except Exception as e:
            logger.error(f"Failed to load pi0 model: {e}")
            
    def compute_action_chunk(self, observation_image, instruction: str, visual_prompt_mask=None) -> np.ndarray:
        """
        Takes the current observation (with injected visual prompts!) and the semantic instruction,
        and generates a sequence of actions (action chunk).
        
        Args:
            observation_image (np.ndarray): Current RGB frame
            instruction (str): Text instruction, e.g., "Grasp the {obj} with {z_offset} offset and {force} force"
            visual_prompt_mask (np.ndarray or dict): Optional mask or bbox array generated by Vision Agent
            
        Returns:
            np.ndarray: Action chunk, typically shape [chunk_size, action_dim]
        """
        # [VLA^2 Optimization]: Handle Unseen Concepts via Visual Prompting
        if visual_prompt_mask is not None:
            logger.info("    -> [VLA^2 Feature] Applying explicit visual prompt mask to observation to highlight unseen concepts/targets.")
            # In a real implementation, we would overlay the colored mask onto the RGB image here:
            # observation_image = cv2.addWeighted(observation_image, 0.7, visual_prompt_mask, 0.3, 0)
        
        if not self.is_loaded:
            logger.warning("Pi0 not fully loaded, returning dummy action chunks for testing/simulation.")
            # Dummy 6 DoF + 1 Gripper action
            return np.zeros((10, 7))
        
        # In actual implementation:
        # 1. We composite the visual_prompt_mask onto the observation_image.
        # 2. We pass the image and instruction to `self.model.sample(obs, text)`.
        logger.info(f"System 1 -> Generating Action Chunk for instruction: '{instruction}'")
        
        if hasattr(self, 'model') and self.model is not None:
            try:
                import torch
                # pi0 requires a specific observation format. 
                # Let's prepare a basic obs dict with the image
                obs = {
                    "image": torch.from_numpy(observation_image).unsqueeze(0), # [1, H, W, C]
                    "state": torch.zeros((1, 6)) # Dummy state for libero if needed
                }
                # Move to device if needed
                device = "cuda" if torch.cuda.is_available() else "cpu"
                
                logger.info(f"System 1 -> Inferencing Pi0 on {device} for instruction: '{instruction}'")
                
                # We need to construct the prompt and sample from the policy
                # openpi typically takes dict obs and text instruction
                action_chunk = self.model.sample(obs, text=instruction)
                
                if isinstance(action_chunk, torch.Tensor):
                    action_chunk = action_chunk.detach().cpu().numpy()
                    
                # Ensure shape matches [chunk_size, 7]
                if len(action_chunk.shape) > 2:
                    action_chunk = action_chunk.squeeze()
                    
                return action_chunk
                
            except Exception as e:
                logger.error(f"Failed to inference Pi0 model: {e}")
                logger.warning("Returning dummy zero action chunk due to inference error.")
                return np.zeros((10, 7))
            
        # Generating a dummy zero action chunk for structural integration
        return np.zeros((10, 7))
